name: Build protocol

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Export Properties
      id: properties
      shell: bash
      run: |
        PROPERTIES="$(./gradlew properties --console=plain -q)"
        VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
        echo "::set-output name=version::$VERSION"
        echo "SPP_PROTOCOL_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Release Draft
      if: github.ref == 'refs/heads/master'
      id: createDraft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.SPP_PROTOCOL_VERSION }}
        release_name: v${{ env.SPP_PROTOCOL_VERSION }}
        draft: true
